name: Release

on:
  push:
    tags:
    - "v*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
      - name: Compile
        id: compile
        uses: rust-build/rust-build.action@7d5b0c135ddb825f7692d4d2d75e598184d15cec
        with:
          RUSTTARGET: x86_64-unknown-linux-musl
